server:
  port: 8080
contextPath: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javahibernateclase3?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        maximum-pool-size: 5
        connection-timeout: 60000
        pool-name: notification-pool
        minimum-idle: 2
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect